### ISSUE TITLE
macOS issue: ffmpeg not found 

### ISSUE THREAD

**Issue by enzyme69** [britalmeida/blender_addon_push_to_talk#21]
<img width="888" alt="Screenshot 2023-12-08 at 8 44 59 am" src="https://github.com/britalmeida/push_to_talk/assets/3952687/432e133c-f7d5-474a-aaef-e6e8c8ea4ab7">
<img width="662" alt="Screenshot 2023-12-08 at 8 44 40 am" src="https://github.com/britalmeida/push_to_talk/assets/3952687/9f5d3ab0-d9d9-4ca4-85ed-12bbc0e74bdb">

On macOS, I think ffmpeg issue still persist. Even if I install it through Python Module Manager addon, it does not seem to work.

**Comment by britalmeida** [comment]
Hi @enzyme69
I'm not familiar with that addon. Does it make ffmpeg available as a command line to the system?

Push to Talk runs ffmpeg as an OS process. Meaning, as if from a command line. It doesn't import a Python ffmpeg module.
You can try opening a Terminal and typing `ffmpeg`? If that doesn't work, you'll need to `brew install ffmpeg`.

**Comment by Zophiekat** [comment]
hi i ran into this same issue, in MacOS, the addon wasn't able to find the ffmpeg path. i fixed it by editing the line in the _init_.py file to make it look for "/usr/local/bin/ffmpeg" specifically

`log = logging.getLogger(__name__)
os_platform = platform.system()  # 'Linux', 'Darwin', 'Java', 'Windows'
supported_platforms = {'Linux', 'Darwin', 'Windows'}
ffmpeg_exe_path = "/usr/local/bin/ffmpeg"
`

performing this change was able to load the module successfully.

**Comment by allisonwhilden** [comment]
Thank you @Zophiekat! That worked for me. As I installed ffmpeg via homebrew, I changed the path to `"/opt/homebrew/bin/ffmpeg"`, and then it worked successfully.

**Comment by britalmeida** [comment]
The addon _should_ work with ffmpeg installed via homebrew (it does for me).

@Zophiekat / @allisonwhilden is there any error or odd path reported in the console?

If you'd change the addon code to:
```python
print("Finding ffmpeg path...")
ffmpeg_exe_path = shutil.which("ffmpeg")
print(ffmpeg_exe_path)
```

And run Blender from a terminal to see the output? (adjust for your Blender version)
```bash
cd /Applications/Blender/4.1.1-candidate/Blender.app/Contents/MacOS
./Blender
```


In my testing it's correctly finding the homebrew path:
```
Finding ffmpeg path...
/opt/homebrew/bin/ffmpeg
```

**Comment by neoandthematrix** [comment]
@britalmeida I ran blender from a terminal window, it did find homebrew ffmpeg's path and the plugin worked. But when I ran blender by clicking the blender icon, it couldn't find ffmpeg's path. Maybe the launcher has a different set of environment variables than the terminal?

**Comment by britalmeida** [comment]
That's good info, thank you!

I am currently having some computerless time off :) I can take a look again in August with this information.

**Comment by britalmeida** [comment]
I can confirm the addon is not being able to find ffmpeg when Blender is launched by double-clicking the GUI instead of launched from the terminal.
This is totally not good :(

I can see that the macOS GUI launch has a very minimal PATH environment variable, without `'/opt/homebrew/bin'` or anything else from `.zshrc`.
For reference, this what I get in Blender's Python Console:
```
>>> import os
>>> os.environ["PATH"]
>>> '/usr/bin:/bin:/usr/sbin:/sbin'
```
I'm not sure this is what's expected. On one hand, it makes sense that a GUI launch does get context from specific shell environments, on the other hand, it's not what Linux does and it was unexpected for me. Afaik, homebrew is usually added to the shell's configuration when installed.

Maybe Blender itself should behave differently and have the shell configuration or at least homebrew, I don't know. But - regardless of how unexpected it is and if it should be fixed elsewhere - homebrew is not guaranteed to be in the PATH now :)
**I think it's best for the addon to also look in the usual homebrew path automatically** and **also provide a user option for adding a custom path** to a custom ffmpeg install in any OS.
I'll do that :)

Thank you for your patience! It's been a long computer break for me.

**Comment by britalmeida** [comment]
I've fixed the issue by automatically searching the homebrew directory.
I've decided against also adding the user option for a custom path as I felt it adds more complexity than helps.

Note: on my mac the audio is sounding noticeably glitchy, so please wait for that to be looked into as well. 🙏
